version: '3.7'

services:
  rotki:
    image: rotki/rotki:latest
    environment:
      - TZ=America/New_York
      - ROTKI_ACCEPT_DOCKER_RISK=1
    ports:
      - "12022:80"
    volumes:
      - rotki-data:/data
      - rotki-logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  rotki-data:
  rotki-logs:
